apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: tools
  name: k8s-ri-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "watch", "list"] 
