apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-ri-crb
  namespace: tools
subjects:
- kind: ServiceAccount
  name: k8s-ri
  apiGroup: ""
  namespace: tools
roleRef:
  kind: ClusterRole
  name: k8s-ri-reader
  apiGroup: rbac.authorization.k8s.io 
